-- MySQL Script generated by MySQL Workbench
-- Thu Jan 11 11:43:36 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema analyze
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `analyze` ;

-- -----------------------------------------------------
-- Schema analyze
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `analyze` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `analyze` ;

-- -----------------------------------------------------
-- Table `analyze`.`productCategory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `analyze`.`productCategory` ;

CREATE TABLE IF NOT EXISTS `analyze`.`productCategory` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `analyze`.`productType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `analyze`.`productType` ;

CREATE TABLE IF NOT EXISTS `analyze`.`productType` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `analyze`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `analyze`.`product` ;

CREATE TABLE IF NOT EXISTS `analyze`.`product` (
  `productId` VARCHAR(20) NOT NULL,
  `productName` VARCHAR(50) NOT NULL,
  `price` INT NOT NULL default 0,
  `barcode` VARCHAR(20) NULL DEFAULT NULL,
  `brand` VARCHAR(50) NOT NULL,
  `productCategory` INT NULL DEFAULT NULL,
  `productType` INT NULL DEFAULT NULL,
  `isLaunch` INT NOT NULL DEFAULT 0,
  `qty` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`productId`),
  UNIQUE INDEX `productId` (`productId` ASC) VISIBLE,
  INDEX `product_productCategory_idx` (`productCategory` ASC) VISIBLE,
  INDEX `product_productType_idx` (`productType` ASC) VISIBLE,
  CONSTRAINT `product_productCategory`
    FOREIGN KEY (`productCategory`)
    REFERENCES `analyze`.`productCategory` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `product_productType`
    FOREIGN KEY (`productType`)
    REFERENCES `analyze`.`productType` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `analyze`.`ecommerce`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `analyze`.`ecommerce` ;

CREATE TABLE IF NOT EXISTS `analyze`.`ecommerce` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `website` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `analyze`.`salesdata`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `analyze`.`salesdata` ;

CREATE TABLE IF NOT EXISTS `analyze`.`salesdata` (
  `trx_id` INT NOT NULL AUTO_INCREMENT,
  `ec_id` INT NOT NULL,
  `ec_orderNumber` VARCHAR(100) NOT NULL,
  `ec_productCode` VARCHAR(50) NOT NULL,
  `productId` VARCHAR(50) NOT NULL,
  `productName` VARCHAR(50) NOT NULL,
  `ec_productCategory` VARCHAR(50) NULL DEFAULT NULL,
  `ec_productType` VARCHAR(50) NULL DEFAULT NULL,
  `ec_warehouse` VARCHAR(50) NOT NULL DEFAULT '轉',
  `ec_salesQty` INT NOT NULL,
  `ec_salesPrice` INT NOT NULL,
  `ec_salesDate` DATETIME NOT NULL,
  `ec_salesStatus` VARCHAR(50) NOT NULL,
  `createTime` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`trx_id`),
  UNIQUE INDEX `orderNumber` (`ec_orderNumber` ASC) VISIBLE,
  UNIQUE INDEX `productId` (`productId` ASC) VISIBLE,
  UNIQUE INDEX `productCodeMomo_UNIQUE` (`ec_productCode` ASC) VISIBLE,
  INDEX `salesdata_ec_id_idx` (`ec_id` ASC) VISIBLE,
  CONSTRAINT `salesdata_ec_id`
    FOREIGN KEY (`ec_id`)
    REFERENCES `analyze`.`ecommerce` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sales_productId`
    FOREIGN KEY (`productId`)
    REFERENCES `analyze`.`product` (`productId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `analyze`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `analyze`.`user` ;

CREATE TABLE IF NOT EXISTS `analyze`.`user` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `level` INT NOT NULL default 1,
  PRIMARY KEY (`userId`),
  UNIQUE INDEX `username` (`username` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 101
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `analyze`.`stock`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `analyze`.`stock` ;

CREATE TABLE IF NOT EXISTS `analyze`.`stock` (
  `product_id` VARCHAR(50) NOT NULL,
  `ec_id` INT NOT NULL,
  `qty` INT NOT NULL,
  `ec_qty` INT NOT NULL,
  PRIMARY KEY (`product_id`, `ec_id`),
  INDEX `stock_ec_id_idx` (`ec_id` ASC) VISIBLE,
  CONSTRAINT `stock_product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `analyze`.`product` (`productId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `stock_ec_id`
    FOREIGN KEY (`ec_id`)
    REFERENCES `analyze`.`ecommerce` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
